name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main   # deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # optional, override default wrangler.toml
          command: publish